### PR TITLE
Code style and doc fixes

### LINKED ISSUE #100: Code style and doc fixes
Minor code style and doc fixes:
 * Use UPPERCASE_WITH_UNDERSCORES for enum values
 * Remove @see tags that cause javadoc warnings
 * Remove is from boolean field names
 * Fix whitespace and doc formatting
 * Add doc where missing
 * Remove unused `Base` enum

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #100 

Binary incompatible code changes are described by the clirr plugin:
```bash
$ mvn clirr:check
...
[INFO] --- clirr-maven-plugin:2.6.1:check (default-cli) @ bdg-formats ---
[INFO] Comparing to version: 0.9.0
[ERROR] 8001: o.b.f.avro.Base: Class org.bdgenomics.formats.avro.Base removed
[ERROR] 6001: o.b.f.avro.Feature: Removed field isCircular
[ERROR] 7002: o.b.f.avro.Feature: Method 'public java.lang.Boolean getIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature: Method 'public void setIsCircular(java.lang.Boolean)' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: Method 'public org.bdgenomics.formats.avro.Feature$Builder clearIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: Method 'public java.lang.Boolean getIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: Method 'public boolean hasIsCircular()' has been removed
[ERROR] 7002: o.b.f.avro.Feature$Builder: Method 'public org.bdgenomics.formats.avro.Feature$Builder setIsCircular(java.lang.Boolean)' has been removed
[ERROR] 6001: o.b.f.avro.Genotype: Removed field isPhased
[ERROR] 7002: o.b.f.avro.Genotype: Method 'public java.lang.Boolean getIsPhased()' has been removed
[ERROR] 7002: o.b.f.avro.Genotype: Method 'public void setIsPhased(java.lang.Boolean)' has been removed
[ERROR] 7002: o.b.f.avro.Genotype$Builder: Method 'public org.bdgenomics.formats.avro.Genotype$Builder clearIsPhased()' has been removed
[ERROR] 7002: o.b.f.avro.Genotype$Builder: Method 'public java.lang.Boolean getIsPhased()' has been removed
[ERROR] 7002: o.b.f.avro.Genotype$Builder: Method 'public boolean hasIsPhased()' has been removed
[ERROR] 7002: o.b.f.avro.Genotype$Builder: Method 'public org.bdgenomics.formats.avro.Genotype$Builder setIsPhased(java.lang.Boolean)' has been removed
[ERROR] 6001: o.b.f.avro.GenotypeAllele: Removed field Alt
[ERROR] 6001: o.b.f.avro.GenotypeAllele: Removed field NoCall
[ERROR] 6001: o.b.f.avro.GenotypeAllele: Removed field OtherAlt
[ERROR] 6001: o.b.f.avro.GenotypeAllele: Removed field Ref
[ERROR] 6001: o.b.f.avro.Variant: Removed field isSomatic
[ERROR] 7002: o.b.f.avro.Variant: Method 'public java.lang.Boolean getIsSomatic()' has been removed
[ERROR] 7002: o.b.f.avro.Variant: Method 'public void setIsSomatic(java.lang.Boolean)' has been removed
[ERROR] 7002: o.b.f.avro.Variant$Builder: Method 'public org.bdgenomics.formats.avro.Variant$Builder clearIsSomatic()' has been removed
[ERROR] 7002: o.b.f.avro.Variant$Builder: Method 'public java.lang.Boolean getIsSomatic()' has been removed
[ERROR] 7002: o.b.f.avro.Variant$Builder: Method 'public boolean hasIsSomatic()' has been removed
[ERROR] 7002: o.b.f.avro.Variant$Builder: Method 'public org.bdgenomics.formats.avro.Variant$Builder setIsSomatic(java.lang.Boolean)' has been removed
```

### CODE REVIEW

**Comment by jpdna** [comment]
+1

**Comment by fnothaft** [comment]
LGTM!

**Comment by fnothaft** [comment]
Merged! Thanks @heuermh !

**Comment by heuermh** [comment]
Thanks!

**Pull request merged**
