### PR TITLE
[bdg-formats-37] Adds inferred insert size field.

### LINKED ISSUE #37: AlignmentRecord not storing "TLEN" / "inferred insert size" from BAM
I just noticed this field getting lost when converting into and out of BAMs with ADAM. Should we/I add it? Should we just infer it in ADAM? Or continue not supporting it?

See `TLEN` in the [SAM spec](http://samtools.github.io/hts-specs/SAMv1.pdf).

`htsjdk` puts it in `SAMRecord`s as ["inferred insert size"](https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/samtools/SAMRecord.java#L538)

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #37.

### CODE REVIEW

**Comment by fnothaft** [comment]
Rebased.

**Comment by ilveroluca** [comment]
This field has the same meaning as `Fragment.fragmentSize`.  There can be only one :-)

Come to think of it, `inferredInsertSize` seems like a better name than `fragmentSize`.

**Comment by fnothaft** [comment]
@ilveroluca agreed; however, let's get this in (it resolves a silly issue we've got in ADAM) and then make a later change to harmonize the Fragment and AlignmentRecord types. (Essentially, I'd like to do a bit more profiling before committing to Fragments)

**Comment by fnothaft** [comment]
Manually merged as https://github.com/bigdatagenomics/bdg-formats/commit/e24a8f6b2ae39e07e0f313b43887daf7413f7820.

**Pull request closed without merging**
