### PR TITLE
Add schema for sample

### PR DESCRIPTION
**Pull request by heuermh**
See https://github.com/bigdatagenomics/adam/issues/1039

### CODE REVIEW

**Comment by jpdna** [comment]
see my comment  https://github.com/bigdatagenomics/adam/issues/1039#issuecomment-224128033
about moving `sampleDescription` and `processingDescription` into this `Sample`

**Comment by jpdna** [comment]
@heuermh  - if you want to keep this PR focused on schema you can assign an issue to me to update the ETL code to load and save using the new `Sample` and with these fields in Genotype  moved.

**Comment by heuermh** [comment]
How are those fields populated?  What do they mean?  Do they map to SRA metadata fields, which per earlier conversation and the doc comments all go into `attributes`?

**Comment by jpdna** [comment]
> How are those fields populated?

VCF spec, in context of "5.4.10 Sample mixtures" has
```
##SAMPLE=<ID=Blood,Genomes=Germline,Mixture=1.,Description="Patient germline genome">
```
but I'm not so sure that is going into one of these fields.
I'd suspect they don't get populated now.
However, these two fields `sampleDescription` and `processingDescription` seems reasonable enough in how they are currently described in comments in bdg-formats `genotype` and not expensive there - and can be null

**Comment by heuermh** [comment]
The cardinality for Genomes, Mixture, and Description is 1..*, so they would need to go in array fields.  Or alternatively a single array of Genome records, which would have name, mixture, and description fields.

However, the doc already specifically recommends those go in `attributes`, where cardinality doesn't matter (repeated keys are ok).

**Comment by jpdna** [comment]
> the doc already specifically recommends those go in attributes

putting in attributes is fine with me

**Comment by heuermh** [comment]
Although now that I've said that repeated keys in `attributes` are ok, they are not, since we're using an avro `map<string>`.  In which case last in wins.

**Comment by jpdna** [comment]
I'm not so convinced that these two fields are coming from this  sample mixture related tag anyhow, or that they have any source in VCF currently, so maybe wait to worry about modeling `Genomes, Mixture, Description` cardinality for now until we know more.  

I don't think these fields get populated anyhow - I am more concerned for the principle that in case sample level metadata like this appears in future and somehow are shoe-horned into these fields that it not appear in our inner-inner loop inside of `Genotype`

**Comment by fnothaft** [comment]
Do we want to get this into the next bdg-formats release? CC @heuermh @jpdna

**Comment by heuermh** [comment]
Yes, and #83.  I'll rebase to resolve conflicts in a sec

**Comment by heuermh** [comment]
Attributes with duplicate keys are going to get clobbered.  That wasn't a major issue in the Feature record, where this also came up, but will be here.  The cardinality of the VCF sample attributes and nearly all of the SRA attributes are 0..*.

Is this a reasonable workaround?
```
  // ...
  array<Attribute> attributes = [];
}

record Attribute {
  string key;
  string value;
}
```
or do we want to reopen discussion about a bunch of array fields?

**Comment by heuermh** [comment]
The unit test failure is due to indeterminate sorting.  Is there a way to easily sort by deep compare (nested arrays and maps)?

**Comment by heuermh** [comment]
Thanks!

**Pull request merged**
