### PR TITLE
Lengthen "abbreviated" field names

### PR DESCRIPTION
**Pull request by Gasta88**
As mentioned in issue #126, I edited some fields as requested and added few comments to make the file clearer.

### CODE REVIEW

**Comment by heuermh** [comment]
Jenkins, test this please

**Comment by heuermh** [comment]
@Gasta88 sorry for letting this sit for so long!  I've been letting bdg-formats changes sit until after we get the version 0.23.0 release of ADAM out, which should be only a week or two from today.

**Comment by Gasta88** [comment]
No problem at all, I'm happy to pick other issues when this one is sorted.

**Comment by heuermh** [comment]
Closing in favor of #175, which cherry-picks the commit from this pull request.

**Pull request closed without merging**
